### ISSUE TITLE
Question About Corsica Error in Phoenix Server

### ISSUE THREAD

**Issue by tsubaron** [whatyouhide/corsica#72]
Hello, I am developing using the Phoenix framework and have encountered a problem related to CORS (Cross-Origin Resource Sharing) settings. 

Specifically, I attempted to integrate and configure the Corsica library, but I am encountering errors and it's not functioning correctly.

Firstly, I executed the following commands

```
mix deps.get
mix compile
```

Then, I added Corsica to the MyApp.Endpoint module. Here is the code for that

```
defmodule MyApp.Endpoint do
  use Phoenix.Endpoint, otp_app: :myapp_api

  # CORS Configuration
  plug Corsica

  plug MyApp.Router
end
```

After implementing these settings and starting `mix phx.server`, I am faced with the following compilation error

```
== Compilation error in file lib/myApp/endpoint.ex ==
** (UndefinedFunctionError) function Corsica.init/1 is undefined (module Corsica is not available)
    (corsica 2.1.3) Corsica.init([])
    (plug 1.15.2) lib/plug/builder.ex:341: Plug.Builder.init_module_plug/4
    (plug 1.15.2) lib/plug/builder.ex:322: anonymous fn/5 in Plug.Builder.compile/3
    (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug 1.15.2) lib/plug/builder.ex:320: Plug.Builder.compile/3
    (plug 1.15.2) expanding macro: Plug.Builder.__before_compile__/1
    lib/myApp/endpoint.ex:1: MyApp.Endpoint (module)
```

I would appreciate any insights into the cause of this error or potential solutions. 
If additional information is needed, please let me know.

**Comment by tsubaron** [comment]
resolve it.
